
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UnitsMinModel {
/*
{
  "id": 0,
  "createBy": "",
  "createTime": "",
  "updateBy": "",
  "updateTime": "",
  "delFlag": "",
  "unit": "",
  "parentId": 0,
  "rate": 0
} 
*/

  String? id;
  String? createBy;
  String? createTime;
  String? updateBy;
  String? updateTime;
  String? delFlag;
  String? unit;
  int? parentId;
  int? rate;

  UnitsMinModel({
    this.id,
    this.createBy,
    this.createTime,
    this.updateBy,
    this.updateTime,
    this.delFlag,
    this.unit,
    this.parentId,
    this.rate,
  });
  UnitsMinModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString() ?? '';
    createBy = json['createBy']?.toString()??"";
    createTime = json['createTime']?.toString()??"";
    updateBy = json['updateBy']?.toString()??"";
    updateTime = json['updateTime']?.toString()??"";
    delFlag = json['delFlag']?.toString()??"";
    unit = json['unit']?.toString()??"";
    parentId = int.tryParse(json['parentId']?.toString() ?? '')??0;
    rate = int.tryParse(json['rate']?.toString() ?? '')??0;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['createBy'] = createBy;
    data['createTime'] = createTime;
    data['updateBy'] = updateBy;
    data['updateTime'] = updateTime;
    data['delFlag'] = delFlag;
    data['unit'] = unit;
    data['parentId'] = parentId;
    data['rate'] = rate;
    return data;
  }
}
